### ISSUE TITLE
Force array in JSON Struct

### ISSUE THREAD

**Issue by guilhermecgs** [christianpanton/matlab-json#11]
Hi Folks,

Is there a way to force the code to use JSON Array even if there is only one element?

For example:

struct.child = oneElement

produce something like

"child":[
            {
                   oneElement
            }
            }

**Comment by christianpanton** [comment]
You could remove [this control-structure](https://github.com/christianpanton/matlab-json/blob/master/tojson.c#L94), such that the `num_el == 1` branch is never taken.
