### ISSUE TITLE
The Build Win procedure does not work any longer

### ISSUE THREAD

**Issue by fgunnars** [christianpanton/matlab-json#17]
Hi,

Quite inexperienced, but I cannot install the Windows SDK from the provided link. Do you use an updated SDK when building? I am on Win 7 Enterprise SP1 x64.

/Fredrik

**Comment by Nzbuu** [comment]
I built it yesterday following exactly that procedure. Have you followed the Mathworks instructions for installing the WinSDK?

**Comment by christianpanton** [comment]
Has this been resolved?

**Comment by fgunnars** [comment]
Yes, sorry for not feeding that back,

/Fredrik

torsdag 5 november 2015 skrev Christian Panton <notifications@github.com>:
