### ISSUE TITLE
Exception when JSON key is longer than 63 characters.

### ISSUE THREAD

**Issue by Amrit-Gill** [christianpanton/matlab-json#20]
Please find a JSON here: http://pastebin.com/ZxmyvMdY
I am trying to transform this json into a Matlab structure using:
`fromjson(JsonObject).` 
The output should look something like: `struct.(key) = [<double>]`.
The problem is with the length of key. Matlab does not accept a variable name which is bigger than 63 characters. I was using MD5 with jsonlab (library written in matlab) to transform the key into a string with a lower number of characters. I shifted the matlab-json because of the performance.

Do you have a solution for this problem? I am also trying to add MD5 in C library. I will let you know if I could resolve it.

Thank you

**Comment by christianpanton** [comment]
I acknowledge that the long key names causes problems in MATLAB structs. However, renaming keys is out of scope of this project. You need to pre-process the data or create a fork of the project.

**Comment by Amrit-Gill** [comment]
Thank you for your response, I have decided to pre-process the data.
