### ISSUE TITLE
Struct of struct of vector returns as cell array.

### ISSUE THREAD

**Issue by jerlich** [christianpanton/matlab-json#21]
```matlab 
a.b.c = [5 6];
a.bb.c = [3 56];
s = tojson(a)
s
% s = { "b": { "c": [ 5, 6 ] }, "bb": { "c": [ 3, 6 ] } }
so = fromjson(s);
so.b % c: {2x1 cell}
a.b % c: [5 6]
```

**Comment by jerlich** [comment]
It turns out that even a struct with vector returns as cell array.

**Comment by jerlich** [comment]
I realize that this is not a bug. Some matlab-json implementations assume that if all elements in an array are numeric then it should be imported as a matrix rather than a cell array. I think that assumption is reasonable (and i would prefer that behavior), but it is not obvious that this is strictly the "right thing" to do.

for example if i have a matlab cell `a = {343 23 34 43 23}` and i convert it to json and back, the above assumption will bring it back as a = [343 23 34 43 23].

**Comment by christianpanton** [comment]
This is as intented, since JSON arrays are typeless (and only contain type information by parsing the subtree), the only safe representation in MATLAB is as a cell-array. See also #11
