### ISSUE TITLE
Is there anyway to get this installed on a MAC?

### ISSUE THREAD

**Issue by cryptoscientia** [christianpanton/matlab-json#23]
Is there anyway to get this installed on a MAC?

**Comment by christianpanton** [comment]
Most likely. You need to install libjson-c and then you should be able to compile the functions using Mex. But as I don't have a Mac, I cannot provide any instructions.

**Comment by histed** [comment]
I made changes to compile on Mac.  Easiest to use homebrew to install libjson-c.
